language: node_js
install:
  - yarn
cache:
  directories:
    - travis_phantomjs
node_js:
  - 8.9
script:
  - yarn lint:api
  - yarn lint:ui
  - yarn lint:integration
  - yarn test:api:cover
  - yarn test:ui
  # - yarn test:integration
services:
  - redis-server
after_success:
  - yarn coveralls
  - sh bin/touch-lynbot.sh
addons:
  sauce_connect: true
  hosts:
    - test-easelbee.io
notifications:
  webhooks:
    urls:
     - https://lynbot.easelbee.io/travis
    on_start: always
